### ISSUE TITLE
Question on how to spin up a Docker image for connecting to homebrewery docker image

### ISSUE THREAD

**Issue by rjbprime** [naturalcrit/naturalcrit#5]
Hi all,

How would one set up a docker image to allow for login into a docker image of homebrewery on localhost? I have never created a docker image from scratch, alwas used a prebuilt image, but on the homebrewery subreddit, they mentioned changing a line of code in one of the homebrewery scripts to connect to a locally hosted and running naturalcrit project.

Kind regards

**Comment by earlng** [comment]
I was looking around and trying to figure out the same as you rjbprime. After some digging and poking around in the homebrewery gitter chat, I figured it out.

I created a PR (#6) for some changes that I think would help. So if you are hoping to host via docker, you will be creating a total of 3 containers:

1. Homebrewery
2. NaturalCrit
3. MongoDB

Here is a docker-compose.yml that worked for me:
```yml
version: '2'
services:
  mongodb:
    image: mongo:latest
    volumes:
      - mongodb:/data/db
    networks:
      - homebrewery
  homebrewery:
    build:
      context: ./homebrewery
      dockerfile: Dockerfile
    image: homebrewery
    environment:
      MONGODB_URI: mongodb://mongodb/homebrewery
    ports:
      - "8000:8000"
    depends_on:
      - "mongodb"
    networks:
      - homebrewery
  naturalcrit:
    build:
      context: ./naturalcrit
      dockerfile: Dockerfile
    image: naturalcrit
    environment:
      MONGODB_URI: mongodb://mongodb/naturalcrit
    ports:
      - "8010:8010"
    depends_on:
      - "mongodb"
    networks:
      - homebrewery
networks:
    homebrewery:
        driver: bridge
```

One thing to note on this docker-compose. This docker-compose is in the same directory as the naturalcrit and homebrewery repositories. (that's why the docker-compose `context` is `./homebrewery` and `./naturalcrit` respectively).

Another thing to keep in mind is that my PR, notes, and experience is mostly on getting a live, publicly accessible, version of homeberwery (which you can find [here](http://homebrewery.theglowingfool.com/)). So I am not sure how it all works on just keeping everything on your local network.

Also, make sure to create a `docker.json` in the `/config` directory (as specified in the PR!). Let me know if you have any questions.
